version: 2

updates:
  # Update npm packages
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
    cooldown:
      default-days: 4
    groups:
      eleventy:
        patterns:
          - '@11ty/eleventy'
          - '@x-govuk/nhsuk-eleventy-plugin'
      stylelint:
        patterns:
          - 'stylelint'
          - 'stylelint-config-gds'

  # Update GitHub Actions
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
    groups:
      github-pages:
        patterns:
          - 'actions/configure-pages'
          - 'actions/upload-pages-artifact'
          - 'actions/deploy-pages'
